stages:
  load_dataset:
   cmd: python src/data/load_dataset.py --config=params.yaml
   deps:
   - src/data/load_dataset.py
   - data/initial/labeled.csv
   out:
   - data/raw/data.csv

  clean_dataset:
   cmd: python src/data/clean_dataset.py --config=params.yaml